Fixes #1 basic nsx provider files
IBM-tfproviders/terraform-provider-nsxv pull request #2
Opened 2017-05-03 15:50 UTC by rachappag

2017-05-04 10:16 UTC, chandidas requested changes

2017-05-04 10:16 UTC, chandidas commented on Makefile
> +	go fmt ../govnsx
Do we need to fmt govnsx code from nsx-provider make?

2017-05-04 10:16 UTC, chandidas commented on nsx/config.go
> +		RestAgentName: "govnsx",
RestAgentName should be configurable with some default value "Terraform-Nsx-Provider"

2017-05-04 10:16 UTC, chandidas commented on nsx/config.go
> +	nsxMrgParams := &govnsx.NsxManagerParams{
change to nsxMgrParams

2017-05-04 10:16 UTC, chandidas commented on nsx/config.go
> +	err := c.EnableDebug()
Should not this be called after client object creation?

2017-05-04 11:21 UTC, rachappag commented on Makefile
> +	go fmt ../govnsx
removed fmt exec for govnsx from nsx provider Make file

2017-05-04 11:23 UTC, rachappag commented on nsx/config.go
> +	err := c.EnableDebug()
even before we create the client object create, we need to set the debug related facility to cover the client object creation code too

2017-05-04 11:23 UTC, rachappag commented on nsx/config.go
> +	nsxMrgParams := &govnsx.NsxManagerParams{
changed

2017-05-04 11:23 UTC, rachappag commented on nsx/config.go
> +		RestAgentName: "govnsx",
changed

2017-05-05 10:39 UTC, chandidas approved these changes

2017-05-05 10:39 UTC, merged