Added NSXv Edge support
IBM-tfproviders/terraform-provider-nsxv pull request #6
Opened 2017-05-30 09:48 UTC by sanverm2

2017-05-30 10:29 UTC, rachappag requested changes
We will refactor this implementation into basic edge service and dhcp

2017-06-02 16:18 UTC, rachappag requested changes

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +				ForceNew: false,
We cannot change the type unless we delete and create new edge: ForeNew: true

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +				ForceNew: false,
When datacenter changes, need to delete and create new edge - ForceNew: true

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +					Schema: map[string]*schema.Schema{
We need to provide to room for appliance in HA cluster. Ok to have once appliance for now in case it is large code refactor. We can have another issue for improvement ( to support HA for edge appliance )

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +							ForceNew: false,
Should be good to ForceNew in case we cannot update resource_pool_id in provisioned Edge.

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +							ForceNew: false,
datastore cannot be changed for provisioned edge appliance, If user want to change it should be ForeNew : true

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +								},
Can we add edgeid variable as computed so that other edge service resource can refer it. right now it is stored in provider Id in state file. Id should hold the URI

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +	}
Before returning from Create, Read should be call to ensure the resource is accessible

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +	log.Printf("[INFO] Reading Nsx Edge ")
Get should be call on the resource and sanity/state should be changed

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +func resourceNsxEdgeUpdate(d *schema.ResourceData, meta interface{}) error {
Update need to handle all mutable variables. if it is a big code refactor, we can have a separate issue for it

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge.go
> +	}
Once the resource is deleted Id need to be set to empty string in state file

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge_dhcp.go
> +				Type:         schema.TypeString,
This looks to hold only one subnet. Can we have  a array/map call "subnets" and have cidr, gw, ipool range under it.
Also, any plan to support other dhcp attributes such as dns etc,..

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge_dhcp.go
> +	log.Printf("[INFO] Configured DHCP for NSX Edge: %s", dhcp.edgeId)
We should set the location as Id and computed variable for DHCP edgeID though input variable edgeID and computed variable DhcpEdgeID remain same. However, user can change input edgeID. In that case we need do ForeNew.

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge_dhcp.go
> +
Read is required before returning from Create

2017-06-02 16:18 UTC, rachappag commented on nsx/resource_nsx_edge_dhcp.go
> +	log.Printf("[INFO] Reading Nsx Edge DHCP")
Read should call Get API on the resource, do sanity/state check for consultancy

2017-06-05 09:25 UTC, Kavitha-Subramaniam commented on nsx/resource_nsx_edge.go
> +					Schema: map[string]*schema.Schema{
The current code handles multiple appliance deployment..

2017-06-05 09:50 UTC, Kavitha-Subramaniam commented on nsx/resource_nsx_edge_dhcp.go
> +				Type:         schema.TypeString,
Lets discuss and finalize

2017-06-05 09:57 UTC, Kavitha-Subramaniam commented on nsx/resource_nsx_edge_dhcp.go
> +	log.Printf("[INFO] Configured DHCP for NSX Edge: %s", dhcp.edgeId)
The PUT request doesn't return location..

2017-06-06 12:02 UTC, chandidas requested changes

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +				Required: true,
Add validator for 'type' attribute.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +				Optional: true,
Change tenant_id to 'ForceNew: true'

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +				ForceNew: false,
ForceNew false is default. Explicit statement not needed.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +				ForceNew: false,
ForceNew should be true for 'folder'.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +				Default:  "",
Make 'name' mandatory.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +	edgeCfg := NewNsxEdge(d)
Change NewNsxEdge to parseResourceData.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +		log.Printf("[Error] edge.Post() returned error : %v", err)
Change to more meaningful debug log.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +		return fmt.Errorf("Invalid Edge id to set: %#v", resp.EdgeId)
No need to check error for d.Set API.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +	log.Printf("[Info] edge.Get() returned Edge: %v", retEdge)
Log levels in CAPs.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +		return err
Log error message

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +		log.Printf("[INFO] Updating NsxEdge :name: %s", v)
Change INFO to DEBUG.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +		log.Printf("[INFO] Updating NsxEdge :description: %s", v)
Change INFO to DEBUG.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +		return err
Log ERROR message.

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge.go
> +	if v, ok := d.GetOk("tenant_id"); ok {
Attributes with default values, can be got using get... :)

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge_dhcp.go
> +	d.SetId(dhcp.edgeId)
Value of Id -> "dhcp-$dhcp.edgeId". Check return of d.SetId

2017-06-06 12:02 UTC, chandidas commented on nsx/resource_nsx_edge_dhcp.go
> +func ipToInt(ip net.IP) uint32 {
Move all the utility and common functions to nsx_common.go.

2017-06-14 07:43 UTC, merged