Added NSX Edge Interface create/destroy/get operations
IBM-tfproviders/terraform-provider-nsxv pull request #9
Opened 2017-06-15 08:40 UTC by sanverm2

Added create/read and delete NSX Edge Interface resource.  Work in progress.

TF Resource

resource "nsxv_edge_dlr_interface" "intf1" {
        edge_id = "edge-327"
        name    = "intf1"
        ip = "10.10.10.1"
        mask = "255.255.255.0"
        type = "internal"
        is_connected = true
        portgroup = "virtualwire-210"
}

DOC
resource "nsxv_edge_dlr_interface" "intf1" {
        edge_id = "edge-181" # Mandatory
        name    = "intf1" # Optional, Computed if not provided
        ip = "10.10.10.1" # Mandatory
        mask = "255.255.255.0" # Mandatory
        type = "internal" # internal or uplink,  Optional, defauls to Internal is not provided
        is_connected = true #Optional, sets to false if not provided true.
        portgroup = "virtualwire-210" #Mandatory
}

2017-06-16 07:31 UTC, rachappag commented on nsx/resource_nsx_edge_dlr.go
> +							ForceNew:     true,
We might need to allow IP update for the interface instead of forcenew. For now Forenew is not bad.

2017-06-16 07:31 UTC, rachappag commented on nsx/resource_nsx_edge_dlr.go
> +							ForceNew:     true,
Change in mask can be handled without force new, For initial implementation we can forecenew.

2017-06-16 07:31 UTC, rachappag commented on nsx/resource_nsx_edge_dlr.go
> +			"interface": &schema.Schema{
We can have one more attribute "type": computed
Any operation on this resource will check the edge type. if it is empty, the resource will be verified as "dlr" with backend call and back populated in the state file. If the type is not dlr, stall the operation and throw an error stating the edge instance is not dlr.

2017-06-16 07:31 UTC, rachappag commented on nsx/resource_nsx_edge_dlr_interface.go
> +package nsx
hope this is deleted

2017-06-19 04:23 UTC, sanverm2 commented on nsx/resource_nsx_edge_dlr.go
> +							ForceNew:     true,
Changed to ForceNew false.

2017-06-19 06:46 UTC, rachappag requested changes

2017-06-19 06:46 UTC, rachappag commented on nsx/resource_nsx_edge_dlr.go
> +	edgeType, err := getEdgeType(d.Get("edge_id").(string), meta)
Can we refactor the edge type check in create and back populating the state in Read

2017-06-19 07:55 UTC, sanverm2 commented on nsx/resource_nsx_edge_dlr.go
> +	edgeType, err := getEdgeType(d.Get("edge_id").(string), meta)
Sure Done.

2017-06-19 09:11 UTC, merged